# Nama workflow ini, akan muncul di tab "Actions" di GitHub
name: 'Render KiCad PCB Outputs'

# Pemicu: Kapan workflow ini harus berjalan?
# Di sini, ia akan berjalan setiap kali ada 'push' ke branch 'main'
on:
  push:
    branches:
      - main

# Daftar pekerjaan (jobs) yang akan dilakukan
jobs:
  generate_outputs:
    # Nama pekerjaan, bebas kamu tentukan
    name: Generate Manufacturing Files

    # Menggunakan sistem operasi Ubuntu versi terbaru untuk menjalankan pekerjaan
    runs-on: ubuntu-latest

    # Langkah-langkah (steps) yang akan dieksekusi secara berurutan
    steps:
      # Langkah 1: Mengambil kode/file dari repositorimu
      - name: Checkout repository
        uses: actions/checkout@v4

      # Langkah 2: Menjalankan action utama untuk ekspor KiCad
      - name: Run KiCad Exports Action
        # INI BAGIAN YANG DIPERBAIKI
        uses: INTI-CMNB/actions-kicad-exports@v5 
        with:
          kicad-project-file: 'Universal_Power_Board' 

      # Langkah 3: Mengunggah hasil render sebagai "Artifact"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kicad-manufacturing-files
          path: kicad-exports/
